<?php
/**
 * CreateCampaignRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SouravsspaceUnsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SouravsspaceUnsent\Model;

use \ArrayAccess;
use \SouravsspaceUnsent\ObjectSerializer;

/**
 * CreateCampaignRequest Class Doc Comment
 *
 * @category Class
 * @package  SouravsspaceUnsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateCampaignRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'createCampaign_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'from' => 'string',
        'subject' => 'string',
        'preview_text' => 'string',
        'contact_book_id' => 'string',
        'content' => 'string',
        'html' => 'string',
        'reply_to' => '\SouravsspaceUnsent\Model\CreateCampaignRequestReplyTo',
        'cc' => '\SouravsspaceUnsent\Model\CreateCampaignRequestReplyTo',
        'bcc' => '\SouravsspaceUnsent\Model\CreateCampaignRequestReplyTo',
        'send_now' => 'bool',
        'scheduled_at' => 'string',
        'batch_size' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'from' => null,
        'subject' => null,
        'preview_text' => null,
        'contact_book_id' => null,
        'content' => null,
        'html' => null,
        'reply_to' => null,
        'cc' => null,
        'bcc' => null,
        'send_now' => null,
        'scheduled_at' => null,
        'batch_size' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'from' => false,
        'subject' => false,
        'preview_text' => false,
        'contact_book_id' => false,
        'content' => false,
        'html' => false,
        'reply_to' => false,
        'cc' => false,
        'bcc' => false,
        'send_now' => false,
        'scheduled_at' => false,
        'batch_size' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'from' => 'from',
        'subject' => 'subject',
        'preview_text' => 'previewText',
        'contact_book_id' => 'contactBookId',
        'content' => 'content',
        'html' => 'html',
        'reply_to' => 'replyTo',
        'cc' => 'cc',
        'bcc' => 'bcc',
        'send_now' => 'sendNow',
        'scheduled_at' => 'scheduledAt',
        'batch_size' => 'batchSize'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'from' => 'setFrom',
        'subject' => 'setSubject',
        'preview_text' => 'setPreviewText',
        'contact_book_id' => 'setContactBookId',
        'content' => 'setContent',
        'html' => 'setHtml',
        'reply_to' => 'setReplyTo',
        'cc' => 'setCc',
        'bcc' => 'setBcc',
        'send_now' => 'setSendNow',
        'scheduled_at' => 'setScheduledAt',
        'batch_size' => 'setBatchSize'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'from' => 'getFrom',
        'subject' => 'getSubject',
        'preview_text' => 'getPreviewText',
        'contact_book_id' => 'getContactBookId',
        'content' => 'getContent',
        'html' => 'getHtml',
        'reply_to' => 'getReplyTo',
        'cc' => 'getCc',
        'bcc' => 'getBcc',
        'send_now' => 'getSendNow',
        'scheduled_at' => 'getScheduledAt',
        'batch_size' => 'getBatchSize'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('preview_text', $data ?? [], null);
        $this->setIfExists('contact_book_id', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('html', $data ?? [], null);
        $this->setIfExists('reply_to', $data ?? [], null);
        $this->setIfExists('cc', $data ?? [], null);
        $this->setIfExists('bcc', $data ?? [], null);
        $this->setIfExists('send_now', $data ?? [], null);
        $this->setIfExists('scheduled_at', $data ?? [], null);
        $this->setIfExists('batch_size', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if ((mb_strlen($this->container['from']) < 1)) {
            $invalidProperties[] = "invalid value for 'from', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['subject'] === null) {
            $invalidProperties[] = "'subject' can't be null";
        }
        if ((mb_strlen($this->container['subject']) < 1)) {
            $invalidProperties[] = "invalid value for 'subject', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['contact_book_id'] === null) {
            $invalidProperties[] = "'contact_book_id' can't be null";
        }
        if ((mb_strlen($this->container['contact_book_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'contact_book_id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['content']) && (mb_strlen($this->container['content']) < 1)) {
            $invalidProperties[] = "invalid value for 'content', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['html']) && (mb_strlen($this->container['html']) < 1)) {
            $invalidProperties[] = "invalid value for 'html', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['batch_size']) && ($this->container['batch_size'] > 100000)) {
            $invalidProperties[] = "invalid value for 'batch_size', must be smaller than or equal to 100000.";
        }

        if (!is_null($this->container['batch_size']) && ($this->container['batch_size'] < 1)) {
            $invalidProperties[] = "invalid value for 'batch_size', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CreateCampaignRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string $from from
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }

        if ((mb_strlen($from) < 1)) {
            throw new \InvalidArgumentException('invalid length for $from when calling CreateCampaignRequest., must be bigger than or equal to 1.');
        }

        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }

        if ((mb_strlen($subject) < 1)) {
            throw new \InvalidArgumentException('invalid length for $subject when calling CreateCampaignRequest., must be bigger than or equal to 1.');
        }

        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets preview_text
     *
     * @return string|null
     */
    public function getPreviewText()
    {
        return $this->container['preview_text'];
    }

    /**
     * Sets preview_text
     *
     * @param string|null $preview_text preview_text
     *
     * @return self
     */
    public function setPreviewText($preview_text)
    {
        if (is_null($preview_text)) {
            throw new \InvalidArgumentException('non-nullable preview_text cannot be null');
        }
        $this->container['preview_text'] = $preview_text;

        return $this;
    }

    /**
     * Gets contact_book_id
     *
     * @return string
     */
    public function getContactBookId()
    {
        return $this->container['contact_book_id'];
    }

    /**
     * Sets contact_book_id
     *
     * @param string $contact_book_id contact_book_id
     *
     * @return self
     */
    public function setContactBookId($contact_book_id)
    {
        if (is_null($contact_book_id)) {
            throw new \InvalidArgumentException('non-nullable contact_book_id cannot be null');
        }

        if ((mb_strlen($contact_book_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $contact_book_id when calling CreateCampaignRequest., must be bigger than or equal to 1.');
        }

        $this->container['contact_book_id'] = $contact_book_id;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string|null $content content
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }

        if ((mb_strlen($content) < 1)) {
            throw new \InvalidArgumentException('invalid length for $content when calling CreateCampaignRequest., must be bigger than or equal to 1.');
        }

        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets html
     *
     * @return string|null
     */
    public function getHtml()
    {
        return $this->container['html'];
    }

    /**
     * Sets html
     *
     * @param string|null $html html
     *
     * @return self
     */
    public function setHtml($html)
    {
        if (is_null($html)) {
            throw new \InvalidArgumentException('non-nullable html cannot be null');
        }

        if ((mb_strlen($html) < 1)) {
            throw new \InvalidArgumentException('invalid length for $html when calling CreateCampaignRequest., must be bigger than or equal to 1.');
        }

        $this->container['html'] = $html;

        return $this;
    }

    /**
     * Gets reply_to
     *
     * @return \SouravsspaceUnsent\Model\CreateCampaignRequestReplyTo|null
     */
    public function getReplyTo()
    {
        return $this->container['reply_to'];
    }

    /**
     * Sets reply_to
     *
     * @param \SouravsspaceUnsent\Model\CreateCampaignRequestReplyTo|null $reply_to reply_to
     *
     * @return self
     */
    public function setReplyTo($reply_to)
    {
        if (is_null($reply_to)) {
            throw new \InvalidArgumentException('non-nullable reply_to cannot be null');
        }
        $this->container['reply_to'] = $reply_to;

        return $this;
    }

    /**
     * Gets cc
     *
     * @return \SouravsspaceUnsent\Model\CreateCampaignRequestReplyTo|null
     */
    public function getCc()
    {
        return $this->container['cc'];
    }

    /**
     * Sets cc
     *
     * @param \SouravsspaceUnsent\Model\CreateCampaignRequestReplyTo|null $cc cc
     *
     * @return self
     */
    public function setCc($cc)
    {
        if (is_null($cc)) {
            throw new \InvalidArgumentException('non-nullable cc cannot be null');
        }
        $this->container['cc'] = $cc;

        return $this;
    }

    /**
     * Gets bcc
     *
     * @return \SouravsspaceUnsent\Model\CreateCampaignRequestReplyTo|null
     */
    public function getBcc()
    {
        return $this->container['bcc'];
    }

    /**
     * Sets bcc
     *
     * @param \SouravsspaceUnsent\Model\CreateCampaignRequestReplyTo|null $bcc bcc
     *
     * @return self
     */
    public function setBcc($bcc)
    {
        if (is_null($bcc)) {
            throw new \InvalidArgumentException('non-nullable bcc cannot be null');
        }
        $this->container['bcc'] = $bcc;

        return $this;
    }

    /**
     * Gets send_now
     *
     * @return bool|null
     */
    public function getSendNow()
    {
        return $this->container['send_now'];
    }

    /**
     * Sets send_now
     *
     * @param bool|null $send_now send_now
     *
     * @return self
     */
    public function setSendNow($send_now)
    {
        if (is_null($send_now)) {
            throw new \InvalidArgumentException('non-nullable send_now cannot be null');
        }
        $this->container['send_now'] = $send_now;

        return $this;
    }

    /**
     * Gets scheduled_at
     *
     * @return string|null
     */
    public function getScheduledAt()
    {
        return $this->container['scheduled_at'];
    }

    /**
     * Sets scheduled_at
     *
     * @param string|null $scheduled_at Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')
     *
     * @return self
     */
    public function setScheduledAt($scheduled_at)
    {
        if (is_null($scheduled_at)) {
            throw new \InvalidArgumentException('non-nullable scheduled_at cannot be null');
        }
        $this->container['scheduled_at'] = $scheduled_at;

        return $this;
    }

    /**
     * Gets batch_size
     *
     * @return int|null
     */
    public function getBatchSize()
    {
        return $this->container['batch_size'];
    }

    /**
     * Sets batch_size
     *
     * @param int|null $batch_size batch_size
     *
     * @return self
     */
    public function setBatchSize($batch_size)
    {
        if (is_null($batch_size)) {
            throw new \InvalidArgumentException('non-nullable batch_size cannot be null');
        }

        if (($batch_size > 100000)) {
            throw new \InvalidArgumentException('invalid value for $batch_size when calling CreateCampaignRequest., must be smaller than or equal to 100000.');
        }
        if (($batch_size < 1)) {
            throw new \InvalidArgumentException('invalid value for $batch_size when calling CreateCampaignRequest., must be bigger than or equal to 1.');
        }

        $this->container['batch_size'] = $batch_size;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


