<?php
/**
 * GetDomains200ResponseInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SouravsspaceUnsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SouravsspaceUnsent\Model;

use \ArrayAccess;
use \SouravsspaceUnsent\ObjectSerializer;

/**
 * GetDomains200ResponseInner Class Doc Comment
 *
 * @category Class
 * @package  SouravsspaceUnsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetDomains200ResponseInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getDomains_200_response_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'team_id' => 'string',
        'status' => 'string',
        'region' => 'string',
        'click_tracking' => 'bool',
        'open_tracking' => 'bool',
        'public_key' => 'string',
        'dkim_status' => 'string',
        'spf_details' => 'string',
        'created_at' => 'string',
        'updated_at' => 'string',
        'dmarc_added' => 'bool',
        'is_verifying' => 'bool',
        'error_message' => 'string',
        'subdomain' => 'string',
        'verification_error' => 'string',
        'last_checked_time' => 'string',
        'dns_records' => '\SouravsspaceUnsent\Model\GetDomains200ResponseInnerDnsRecordsInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'team_id' => null,
        'status' => null,
        'region' => null,
        'click_tracking' => null,
        'open_tracking' => null,
        'public_key' => null,
        'dkim_status' => null,
        'spf_details' => null,
        'created_at' => null,
        'updated_at' => null,
        'dmarc_added' => null,
        'is_verifying' => null,
        'error_message' => null,
        'subdomain' => null,
        'verification_error' => null,
        'last_checked_time' => null,
        'dns_records' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'team_id' => false,
        'status' => false,
        'region' => false,
        'click_tracking' => false,
        'open_tracking' => false,
        'public_key' => false,
        'dkim_status' => true,
        'spf_details' => true,
        'created_at' => false,
        'updated_at' => false,
        'dmarc_added' => false,
        'is_verifying' => false,
        'error_message' => true,
        'subdomain' => true,
        'verification_error' => true,
        'last_checked_time' => true,
        'dns_records' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'team_id' => 'teamId',
        'status' => 'status',
        'region' => 'region',
        'click_tracking' => 'clickTracking',
        'open_tracking' => 'openTracking',
        'public_key' => 'publicKey',
        'dkim_status' => 'dkimStatus',
        'spf_details' => 'spfDetails',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'dmarc_added' => 'dmarcAdded',
        'is_verifying' => 'isVerifying',
        'error_message' => 'errorMessage',
        'subdomain' => 'subdomain',
        'verification_error' => 'verificationError',
        'last_checked_time' => 'lastCheckedTime',
        'dns_records' => 'dnsRecords'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'team_id' => 'setTeamId',
        'status' => 'setStatus',
        'region' => 'setRegion',
        'click_tracking' => 'setClickTracking',
        'open_tracking' => 'setOpenTracking',
        'public_key' => 'setPublicKey',
        'dkim_status' => 'setDkimStatus',
        'spf_details' => 'setSpfDetails',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'dmarc_added' => 'setDmarcAdded',
        'is_verifying' => 'setIsVerifying',
        'error_message' => 'setErrorMessage',
        'subdomain' => 'setSubdomain',
        'verification_error' => 'setVerificationError',
        'last_checked_time' => 'setLastCheckedTime',
        'dns_records' => 'setDnsRecords'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'team_id' => 'getTeamId',
        'status' => 'getStatus',
        'region' => 'getRegion',
        'click_tracking' => 'getClickTracking',
        'open_tracking' => 'getOpenTracking',
        'public_key' => 'getPublicKey',
        'dkim_status' => 'getDkimStatus',
        'spf_details' => 'getSpfDetails',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'dmarc_added' => 'getDmarcAdded',
        'is_verifying' => 'getIsVerifying',
        'error_message' => 'getErrorMessage',
        'subdomain' => 'getSubdomain',
        'verification_error' => 'getVerificationError',
        'last_checked_time' => 'getLastCheckedTime',
        'dns_records' => 'getDnsRecords'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('team_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], 'us-east-1');
        $this->setIfExists('click_tracking', $data ?? [], false);
        $this->setIfExists('open_tracking', $data ?? [], false);
        $this->setIfExists('public_key', $data ?? [], null);
        $this->setIfExists('dkim_status', $data ?? [], null);
        $this->setIfExists('spf_details', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('dmarc_added', $data ?? [], false);
        $this->setIfExists('is_verifying', $data ?? [], false);
        $this->setIfExists('error_message', $data ?? [], null);
        $this->setIfExists('subdomain', $data ?? [], null);
        $this->setIfExists('verification_error', $data ?? [], null);
        $this->setIfExists('last_checked_time', $data ?? [], null);
        $this->setIfExists('dns_records', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['team_id'] === null) {
            $invalidProperties[] = "'team_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['public_key'] === null) {
            $invalidProperties[] = "'public_key' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        if ($this->container['dns_records'] === null) {
            $invalidProperties[] = "'dns_records' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The ID of the domain
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the domain
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets team_id
     *
     * @return string
     */
    public function getTeamId()
    {
        return $this->container['team_id'];
    }

    /**
     * Sets team_id
     *
     * @param string $team_id The ID of the team
     *
     * @return self
     */
    public function setTeamId($team_id)
    {
        if (is_null($team_id)) {
            throw new \InvalidArgumentException('non-nullable team_id cannot be null');
        }
        $this->container['team_id'] = $team_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The status of the domain
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets region
     *
     * @return string|null
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string|null $region The region of the domain
     *
     * @return self
     */
    public function setRegion($region)
    {
        if (is_null($region)) {
            throw new \InvalidArgumentException('non-nullable region cannot be null');
        }
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets click_tracking
     *
     * @return bool|null
     */
    public function getClickTracking()
    {
        return $this->container['click_tracking'];
    }

    /**
     * Sets click_tracking
     *
     * @param bool|null $click_tracking Whether click tracking is enabled
     *
     * @return self
     */
    public function setClickTracking($click_tracking)
    {
        if (is_null($click_tracking)) {
            throw new \InvalidArgumentException('non-nullable click_tracking cannot be null');
        }
        $this->container['click_tracking'] = $click_tracking;

        return $this;
    }

    /**
     * Gets open_tracking
     *
     * @return bool|null
     */
    public function getOpenTracking()
    {
        return $this->container['open_tracking'];
    }

    /**
     * Sets open_tracking
     *
     * @param bool|null $open_tracking Whether open tracking is enabled
     *
     * @return self
     */
    public function setOpenTracking($open_tracking)
    {
        if (is_null($open_tracking)) {
            throw new \InvalidArgumentException('non-nullable open_tracking cannot be null');
        }
        $this->container['open_tracking'] = $open_tracking;

        return $this;
    }

    /**
     * Gets public_key
     *
     * @return string
     */
    public function getPublicKey()
    {
        return $this->container['public_key'];
    }

    /**
     * Sets public_key
     *
     * @param string $public_key The public key of the domain
     *
     * @return self
     */
    public function setPublicKey($public_key)
    {
        if (is_null($public_key)) {
            throw new \InvalidArgumentException('non-nullable public_key cannot be null');
        }
        $this->container['public_key'] = $public_key;

        return $this;
    }

    /**
     * Gets dkim_status
     *
     * @return string|null
     */
    public function getDkimStatus()
    {
        return $this->container['dkim_status'];
    }

    /**
     * Sets dkim_status
     *
     * @param string|null $dkim_status The DKIM status of the domain
     *
     * @return self
     */
    public function setDkimStatus($dkim_status)
    {
        if (is_null($dkim_status)) {
            array_push($this->openAPINullablesSetToNull, 'dkim_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dkim_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dkim_status'] = $dkim_status;

        return $this;
    }

    /**
     * Gets spf_details
     *
     * @return string|null
     */
    public function getSpfDetails()
    {
        return $this->container['spf_details'];
    }

    /**
     * Sets spf_details
     *
     * @param string|null $spf_details The SPF details of the domain
     *
     * @return self
     */
    public function setSpfDetails($spf_details)
    {
        if (is_null($spf_details)) {
            array_push($this->openAPINullablesSetToNull, 'spf_details');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('spf_details', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['spf_details'] = $spf_details;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at The creation date of the domain
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string $updated_at The last update date of the domain
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets dmarc_added
     *
     * @return bool|null
     */
    public function getDmarcAdded()
    {
        return $this->container['dmarc_added'];
    }

    /**
     * Sets dmarc_added
     *
     * @param bool|null $dmarc_added Whether DMARC is added
     *
     * @return self
     */
    public function setDmarcAdded($dmarc_added)
    {
        if (is_null($dmarc_added)) {
            throw new \InvalidArgumentException('non-nullable dmarc_added cannot be null');
        }
        $this->container['dmarc_added'] = $dmarc_added;

        return $this;
    }

    /**
     * Gets is_verifying
     *
     * @return bool|null
     */
    public function getIsVerifying()
    {
        return $this->container['is_verifying'];
    }

    /**
     * Sets is_verifying
     *
     * @param bool|null $is_verifying Whether the domain is verifying
     *
     * @return self
     */
    public function setIsVerifying($is_verifying)
    {
        if (is_null($is_verifying)) {
            throw new \InvalidArgumentException('non-nullable is_verifying cannot be null');
        }
        $this->container['is_verifying'] = $is_verifying;

        return $this;
    }

    /**
     * Gets error_message
     *
     * @return string|null
     */
    public function getErrorMessage()
    {
        return $this->container['error_message'];
    }

    /**
     * Sets error_message
     *
     * @param string|null $error_message The error message of the domain
     *
     * @return self
     */
    public function setErrorMessage($error_message)
    {
        if (is_null($error_message)) {
            array_push($this->openAPINullablesSetToNull, 'error_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('error_message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['error_message'] = $error_message;

        return $this;
    }

    /**
     * Gets subdomain
     *
     * @return string|null
     */
    public function getSubdomain()
    {
        return $this->container['subdomain'];
    }

    /**
     * Sets subdomain
     *
     * @param string|null $subdomain The subdomain of the domain
     *
     * @return self
     */
    public function setSubdomain($subdomain)
    {
        if (is_null($subdomain)) {
            array_push($this->openAPINullablesSetToNull, 'subdomain');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subdomain', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subdomain'] = $subdomain;

        return $this;
    }

    /**
     * Gets verification_error
     *
     * @return string|null
     */
    public function getVerificationError()
    {
        return $this->container['verification_error'];
    }

    /**
     * Sets verification_error
     *
     * @param string|null $verification_error The verification error of the domain
     *
     * @return self
     */
    public function setVerificationError($verification_error)
    {
        if (is_null($verification_error)) {
            array_push($this->openAPINullablesSetToNull, 'verification_error');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('verification_error', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['verification_error'] = $verification_error;

        return $this;
    }

    /**
     * Gets last_checked_time
     *
     * @return string|null
     */
    public function getLastCheckedTime()
    {
        return $this->container['last_checked_time'];
    }

    /**
     * Sets last_checked_time
     *
     * @param string|null $last_checked_time The last checked time of the domain
     *
     * @return self
     */
    public function setLastCheckedTime($last_checked_time)
    {
        if (is_null($last_checked_time)) {
            array_push($this->openAPINullablesSetToNull, 'last_checked_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_checked_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_checked_time'] = $last_checked_time;

        return $this;
    }

    /**
     * Gets dns_records
     *
     * @return \SouravsspaceUnsent\Model\GetDomains200ResponseInnerDnsRecordsInner[]
     */
    public function getDnsRecords()
    {
        return $this->container['dns_records'];
    }

    /**
     * Sets dns_records
     *
     * @param \SouravsspaceUnsent\Model\GetDomains200ResponseInnerDnsRecordsInner[] $dns_records The DNS records of the domain
     *
     * @return self
     */
    public function setDnsRecords($dns_records)
    {
        if (is_null($dns_records)) {
            throw new \InvalidArgumentException('non-nullable dns_records cannot be null');
        }
        $this->container['dns_records'] = $dns_records;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


