#!/bin/bash
set -e

# Ensure we are in the sdk root or handle paths correctly
# This script assumes it's run from the cli/php-sdk directory or we can find the schema relative to it.

SCHEMA_PATH="../../apps/docs/public/api-reference.json"
TEMP_DIR=".openapi-temp"
TYPES_OUTPUT_FILE="src/Types.php"

echo "Generating PHP types from ${SCHEMA_PATH}..."

# check if schema exists
if [ ! -f "$SCHEMA_PATH" ]; then
    echo "Error: Schema file not found at $SCHEMA_PATH"
    exit 1
fi

# Check if pnpm is available
if ! command -v pnpm &> /dev/null; then
    echo "Error: pnpm not found. Please install Node.js and pnpm."
    exit 1
fi

# Clean up temp directory if it exists
rm -rf "$TEMP_DIR"

# Generate PHP client using openapi-generator-cli to temp directory
# We want the models to use as types in the SDK
echo "Generating model classes..."
pnpm dlx @openapitools/openapi-generator-cli generate \
  -i "$SCHEMA_PATH" \
  -g php \
  -o "$TEMP_DIR" \
  --global-property models,modelDocs=false,modelTests=false \
  --additional-properties=invokerPackage=Souravsspace\\Unsent,packageName=Unsent,modelPackage=Model

# Find the generated Model directory
MODEL_DIR=""
if [ -d "$TEMP_DIR/lib/Model" ]; then
    MODEL_DIR="$TEMP_DIR/lib/Model"
    BASE_SRC_DIR="$TEMP_DIR/lib"
elif [ -d "$TEMP_DIR/src/Model" ]; then
    MODEL_DIR="$TEMP_DIR/src/Model"
    BASE_SRC_DIR="$TEMP_DIR/src"
elif [ -d "$TEMP_DIR/Model" ]; then
    MODEL_DIR="$TEMP_DIR/Model"
    BASE_SRC_DIR="$TEMP_DIR"
else 
    echo "Error: Could not find generated models in expected locations."
    find "$TEMP_DIR" -maxdepth 3
    exit 1
fi

echo "Combining model files from $MODEL_DIR into $TYPES_OUTPUT_FILE..."

# Create the consolidated types file
cat > "$TYPES_OUTPUT_FILE" << 'EOF'
<?php
/**
 * Auto-generated types from OpenAPI schema
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Souravsspace\Unsent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Souravsspace\Unsent\Model;

use \ArrayAccess;
use \Souravsspace\Unsent\ObjectSerializer;

EOF

# Process each model file and append to Types.php
for model_file in "$MODEL_DIR"/*.php; do
    if [ -f "$model_file" ]; then
        echo "Processing $(basename "$model_file")..."
        
        # Extract the class definition (skip the opening <?php tag, comments, namespace, and use statements)
        # We want everything after the initial boilerplate
        awk '
            BEGIN { in_class = 0; skip_lines = 0 }
            /^<\?php/ { next }
            /^\/\*\*/ && !in_class { 
                # Skip comment blocks before class definition
                while (getline && !/\*\//) { }
                next
            }
            /^namespace / { next }
            /^use / { next }
            /^class / { in_class = 1 }
            in_class { print }
        ' "$model_file" >> "$TYPES_OUTPUT_FILE"
        
        # Add spacing between classes
        echo -e "\n" >> "$TYPES_OUTPUT_FILE"
    fi
done

# Copy supporting files (ObjectSerializer, ModelInterface)
echo "Copying supporting files from $BASE_SRC_DIR to src/..."
if [ -f "$BASE_SRC_DIR/ObjectSerializer.php" ]; then
    cp "$BASE_SRC_DIR/ObjectSerializer.php" "src/"
    echo "✓ Copied ObjectSerializer.php"
else
    echo "⚠ Warning: ObjectSerializer.php not found"
fi

if [ -f "$BASE_SRC_DIR/ModelInterface.php" ]; then
    cp "$BASE_SRC_DIR/ModelInterface.php" "src/"
    echo "✓ Copied ModelInterface.php"
else
    echo "⚠ Warning: ModelInterface.php not found"
fi

# Remove old Model directory if it exists
if [ -d "src/Model" ]; then
    echo "Removing old src/Model directory..."
    rm -rf "src/Model"
fi

# Cleanup
rm -rf "$TEMP_DIR"

echo ""
echo "✓ Types consolidated at ${TYPES_OUTPUT_FILE}"
echo "✓ Supporting files copied to src/"
echo "✓ Old Model directory removed"
echo ""
echo "Next step: Update SDK service files to import and use these Model types"
